# Generated by Django 4.1.1 on 2022-09-27 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_book_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='bday',
        ),
        migrations.RemoveField(
            model_name='book',
            name='num_pages',
        ),
        migrations.RemoveField(
            model_name='book',
            name='pub_date',
        ),
    ]
